// <auto-generated />
using System;
using InfoTrack.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfoTrack.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190416155748_InitCreate")]
    partial class InitCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("InfoTrack.DAL.Entities.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Keyword")
                        .IsRequired();

                    b.Property<DateTime>("SearchDate");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SearchHistories");
                });

            modelBuilder.Entity("InfoTrack.DAL.Entities.SearchMatch", b =>
                {
                    b.Property<Guid>("SearchHistoryId");

                    b.Property<int>("Entry");

                    b.HasKey("SearchHistoryId", "Entry");

                    b.ToTable("SearchMatch");
                });

            modelBuilder.Entity("InfoTrack.DAL.Entities.SearchMatch", b =>
                {
                    b.HasOne("InfoTrack.DAL.Entities.SearchHistory", "SearchHistory")
                        .WithMany("SearchMatches")
                        .HasForeignKey("SearchHistoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
